# Generated by Django 3.1.5 on 2022-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pcp',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
