# Generated by Django 3.1.5 on 2022-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scw', '0002_auto_20220716_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
